Create a 2D NumPy array and assign values. Then print the values.

In [1]:
import numpy as np 

In [3]:
array = np.array([[58,98,89,2585,8],[78,5,69,869,8755],[78,585,485,5,87]])

In [4]:
print(array)

[[  58   98   89 2585    8]
 [  78    5   69  869 8755]
 [  78  585  485    5   87]]
