Perform matrix multiplication between two 2D NumPy arrays

In [26]:
import numpy as np

In [27]:
array1 = np.array([[2,4,4],[3,3,6],[8,9,6]])

print("Array 1 : \n",array1)

Array 1 : 
 [[2 4 4]
 [3 3 6]
 [8 9 6]]


In [28]:
array2 = np.array([[8,5,2],[9,6,4],[2,4,6]]);

print("Array 2 \n ",array2)

Array 2 
  [[8 5 2]
 [9 6 4]
 [2 4 6]]


In [29]:
matrix_multiplication = np.matmul( array1, array2)

In [30]:
print ("Resultant Matrix \n " ,matrix_multiplication)

Resultant Matrix 
  [[ 60  50  44]
 [ 63  57  54]
 [157 118  88]]
